config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts, except: [:new]
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if !user.new_record?
      can :manage, Post, { user_id: user.id }
      can :create, Post
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  searchkick
  belongs_to :user

  has_rich_text :content

  validates_presence_of :content, :user

  def search_data
    {
      title: title,
      content: content
    }
  end

  def editor_content
    self.try(:content).try(:body)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  validates :password_confirmation, presence: true, on: :create
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  private
    def authenticated_user!
      session['user_return_to'] = request.fullpath
      if user_signed_in?
        authenticate_user!
      else
        redirect_to new_user_session_path, notice: 'Please Login to view that page!'
      end
    end

    # Deletes the return path as soon as it's used, so
    # they aren't accidentally redirected back again
    # next time they login

    def after_sign_in_path_for(resource)
      session.delete('user_return_to') || root_path
    end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @post = Post.new
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticated_user!
  load_and_authorize_resource
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @posts = Posts::PostManage.new(current_user, params[:search]).get_posts
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = 'Post was successfully created.'
      redirect_to @post
    else
      flash[:error] = @post.errors.full_messages
      render 'home/index'
    end
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Post was successfully updated.'
      redirect_to @post
    else
      flash[:error] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:notice] = 'Post was successfully destroyed.'
      redirect_to posts_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_user.posts.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def post_params
      params.fetch(:post, {}).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def form_title(post)
    post.new_record? ? 'Create your content to print' : 'Edit your post'
  end

  def post_thumb_content(post)
    truncate(strip_tags(post.editor_content.to_s), length: 100)
  end

  def post_content(post)
    post.editor_content.try(:html_safe)
  end

  def post_time_created(post)
    time_ago_in_words(post.created_at)
  end
end

app/views/active_storage/blobs/_blob.html.haml
%figure{:class => "attachment attachment--#{blob.representable? ? "preview" : "file"} attachment--#{blob.filename.extension}"}
  - if blob.representable?
    = image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])
  %figcaption.attachment__caption
    - if caption = blob.try(:caption)
      = caption
    - else
      %span.attachment__name= blob.filename
      %span.attachment__size= number_to_human_size blob.byte_size

app/views/home/index.html.haml
= render 'posts/form', post: @post

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DecoupagePage
    = csrf_meta_tags
    = csp_meta_tag
    %link{rel: "stylesheet", href: "https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css", integrity: "sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk", crossorigin: "anonymous"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "https://code.jquery.com/jquery-3.4.1.slim.min.js", integrity:"sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n", crossorigin:"anonymous"}
    %script{src: "https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js", integrity: "sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI", crossorigin: "anonymous"}
    = tinymce_assets

  %body
    = render partial: 'layouts/page/header'
    %main.container
      - flash.each do |type, content|
        - if content.respond_to?('each')
          - content.each do |item|
            = render 'layouts/page/flash_msg', type: type, content: item
        - else
          = render 'layouts/page/flash_msg', type: type, content: content
      = yield
    = render partial: 'layouts/page/footer'

app/views/layouts/page/_flash_msg.html.haml
%div#myAlert{class: "alert #{bootstrap_class_for(type)} alert-dismissible fade show", role: "alert"}
  %button.close{"data-aria-label": "Close", "data-dismiss": "alert", type: "button"}
    %span{"aria-hidden": "true"} ×
  .text
    = content

app/views/layouts/page/_header.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-dark.fixed-top
  %a.navbar-brand{:href => root_path} Decoupage Editor
  %button.navbar-toggler{"aria-controls" => "navbarsExampleDefault", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarsExampleDefault", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarsExampleDefault.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item
        %a.nav-link{:href => "#"} Link
      %li.nav-item
        %a.nav-link.disabled{"aria-disabled" => "true", :href => "#", :tabindex => "-1"} Disabled
      = form_with( url: posts_path, class: "form-inline", method: :get,local: true) do |f|
        = f.text_field :search, value: params[:search], placeholder: "Search", class: "form-control mr-sm-2"
        = f.submit "Search", class: "btn btn-secondary my-2 my-sm-0"
    .my-2.my-lg-0
      #mySidenav.sidenav
        %a.closebtn{:href => "javascript:void(0)", :onclick => "closeNav()"} ×
        = link_to "Posts", posts_path
        = render partial: "layouts/page/registration_items"
        = render partial: "layouts/page/login_items"
      %span.menu-button{onclick: "openNav()"}=image_tag "menu-hamburger.svg"

app/views/layouts/page/_login_items.html.haml
- if user_signed_in?
  %li
    = link_to('Logout', destroy_user_session_path, method: :delete)
- else
  %li
    = link_to('Login', new_user_session_path)

app/views/layouts/page/_registration_items.html.haml
- if user_signed_in?
  %li
    = link_to('Profile', edit_user_registration_path)
- else
  %li
    = link_to('Register', new_user_registration_path)

app/views/posts/_action_buttons.html.haml
.actions
  = link_to 'Edit', edit_post_path(post), class: "btn btn-outline-primary"
  = link_to 'Print', "#", 'onclick': "window.print();return false;", class: "btn btn-outline-primary"
  = link_to 'Back', posts_path, class: "btn btn-outline-default"

app/views/posts/_form.html.haml
= form_with(model: @post, local: true) do |form|
  %h2= form_title(@post)
  .field
    = form.text_area :content, class: "tinymce", id:"editor", value: post_content(@post)

  .actions
    = form.submit class: "btn btn-primary" if can? :create, @post

app/views/posts/edit.html.haml
= render 'form', post: @post

app/views/posts/index.html.haml
.album
  %h2 All posts
  .row
    -@posts.each do |post|
      .col-md-4
        .card
          .card-body
            %h5.card-title Card title
            %p.card-text= post_thumb_content(post)
            - if can? :read, post
              = link_to "Show Page", post_path(post), class: "card-link"
            - if can? :destroy, post
              = link_to "Delete Page", post_path(post), method: :delete, data: {confirm: "Are you sure?"}, class: "card-link"
            %small.text-muted= post_time_created(post)

app/views/posts/show.html.haml
.container-fluid
  .noprint= render 'action_buttons', post: @post
  .page.A4
    = post_content(@post)
  .noprint= render 'action_buttons', post: @post